yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [path('',
                    views.index,
                    name='index'
                    ),
               path('group/<slug:slug>/',
                    views.group_posts,
                    name='group_list'
                    ),
               # Профайл пользователя
               path('profile/<str:username>/',
                    views.profile,
                    name='profile'
                    ),
               # Просмотр записи
               path('posts/<int:post_id>/',
                    views.post_detail,
                    name='post_detail'
                    ),
               # Создание записи
               path('create/',
                    views.post_create,
                    name='post_create'
                    ),
               # Редактирование записи
               path('posts/<int:post_id>/edit/',
                    views.post_edit,
                    name='post_edit'
                    ),
               ]

yatube/users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetDoneView, PasswordChangeView,
    PasswordChangeDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        # View класс стандартный, шаблон страницы наш
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Административная панель
    path('admin/', admin.site.urls),
    # Переопределение стандартных шаблонов авторизации
    path('auth/', include('users.urls', namespace='users')),
    # Стандартные шаблоны авторизации
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
]

yatube/templates/includes/error_control.html
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}

yatube/templates/includes/footer.html
<!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
        <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
      </footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}  
        <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
              href="{% url 'about:author' %}"
              >
                Об авторе
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}"
              >
                Технологии
            </a>
          </li>
          {%  if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}"
              >
                Новая запись
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}"
              href="{% url 'users:password_change' %}"
              >
                Изменить пароль
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light"
              href="{% url 'users:logout' %}"
              >
                Выйти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light"
              href="{% url 'posts:profile' user.username %}"
              >
                Пользователь: {{ user.username }}
            </a>
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
              href="{% url 'users:login' %}"
              >
                Войти
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}"
              >
                Регистрация
            </a>
          </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
   </nav>
</header>

yatube/templates/includes/one_field_form.html
                <div class="form-group row my-3"
                  {% if field.field.required %} 
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}

                <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                        <span class="required text-danger">*</span>
                    {% endif %}
                    </label>    
                    {{ field }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                    </small>
                    {% endif %}
                </div>

yatube/templates/includes/one_post.html
<ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a></br>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}