yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [path('',
                    views.index,
                    name='index'
                    ),
               path('group/<slug:slug>/',
                    views.group_posts,
                    name='group_list'
                    ),
               # Профайл пользователя
               path('profile/<str:username>/',
                    views.profile,
                    name='profile'
                    ),
               # Просмотр записи
               path('posts/<int:post_id>/',
                    views.post_detail,
                    name='post_detail'
                    ),
               # Создание записи
               path('create/',
                    views.post_create,
                    name='post_create'
                    ),
               # Редактирование записи
               path('posts/<int:post_id>/edit/',
                    views.post_edit,
                    name='post_edit'
                    ),
               ]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Административная панель
    path('admin/', admin.site.urls),
    # Переопределение стандартных шаблонов авторизации
    path('auth/', include('users.urls', namespace='users')),
    # Стандартные шаблоны авторизации
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    class Meta:
        default_related_name = 'posts'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django import forms
from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        # Эта форма будет работать с моделью Post
        model = Post
        # Поля модели, которые должны отображаться в веб-форме
        fields = ('text', 'group')

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from posts.models import Post, Group
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
# Импортируем глобальные настройки
from django.conf import settings
# Импортируем класс формы, чтобы сослаться на неё во view-классе
from posts.forms import PostForm


def paginate_page(request, posts):
    # Получаем набор из OBJECTS_ON_THE_PAGE записей
    # для страницы page из request
    page_number = request.GET.get('page')
    paginator = Paginator(posts, settings.OBJECTS_ON_THE_PAGE)
    return paginator.get_page(page_number)


def index(request):
    # Получаем выборку из всех объектов модели Post,
    # подразумевается, что сортировка по полю pub_date
    # по убыванию прописана в классе Meta модели.
    # Сразу запрашиваем связанные объекты group и author
    posts = Post.objects.select_related('group', 'author')
    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginate_page(request, posts)
    return render(request, 'posts/index.html', {'page_obj': page_obj})


def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    group = get_object_or_404(Group, slug=slug)
    # .posts - related_name поля group класса Post
    posts = group.posts.select_related('author')
    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginate_page(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginate_page(request, posts)
    context = {
        'page_obj': page_obj,
        'author': author,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/post_detail.html', {'post': post})


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(
        request,
        'posts/create_post.html',
        {'form': form, 'is_edit': False}
    )


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if not post.author == request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post_pk': post_id
    }
    return render(request, 'posts/create_post.html', context)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block pagetitle %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
{% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
          Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% include 'includes/error_control.html' %}
          {% endif %}
          <form method="post"
            {% if is_edit %}
              action="{% url 'posts:post_edit' post_pk %}"
            {% else %}
                action="{% url 'posts:post_create' %}"
            {% endif %}
            >
            {% csrf_token %}
            {% for field in form %}
              {% include 'includes/one_field_form.html' %}
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 

yatube/templates/posts/group_list.html
<!-- templates/posts/group_list.html -->
{% extends 'base.html' %}
{% block pagetitle %}
Записи сообщества {{ group }}
{% endblock %}
{% block content %}
  <h1>{{ group }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include 'includes/one_post.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
  {% block pagetitle %}
    Последние обновления на сайте
  {% endblock %}
  {% block content %}
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      {% include 'includes/one_post.html' %}
      {% if post.group%}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  {% endblock %} 

yatube/templates/posts/post_detail.html
<!-- templates/posts/post_detail.html -->
{% extends 'base.html' %}
  {% block pagetitle %}
    {{ post|truncatechars:30 }}
  {% endblock %}
  {% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        <!-- если у поста есть группа -->   
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }} </br>
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }} aka {{ post.author.username }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>{{ post }}</p>
      {% if user == post.author  %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
          редактировать запись
        </a>
      {% endif%}
    </article>
  </div>
  {% endblock %}

yatube/templates/posts/profile.html
<!-- templates/posts/profile.html -->
{% extends 'base.html' %}
  {% block pagetitle %}
    {{ author.get_full_name }} профайл пользователя
  {% endblock %}
  {% block content %}
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% for post in page_obj %}
      {% include 'includes/one_post.html' %}
      {% if post.group%}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  {% endblock %} 